_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "AutoFocusFormer"
  AFF:
    EMBED_DIM: [64,128,256,512]
    DEPTHS: [3,4,18,5]
    NUM_HEADS: [2,4,8,16]
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    MLP_RATIO: 3.
    CLUSTER_SIZE: 8
    NBHD_SIZE: [48,48,48,48]
    ALPHA: 4.0
    DS_RATE: 0.2
  WEIGHTS: "aff_tiny_1_5th.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002
  STEPS: (81945, 88773)
  MAX_ITER: 92188 
  WARMUP_ITERS: 3
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
