_BASE_: ../maskformer2_R50_bs16_90k.yaml 
MODEL:
  BACKBONE:
    NAME: "AutoFocusFormer"
  AFF:
    EMBED_DIM: [128, 256, 512, 1024]
    DEPTHS: [3,4,18,2]
    NUM_HEADS: [4,8,16,32]
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    MLP_RATIO: 3.
    CLUSTER_SIZE: 24
    NBHD_SIZE: [144,144,144,144]
    LAYER_SCALE: 1e-5 # turned off if 0.0
    ALPHA: 8.0
    DS_RATE: 0.25
  WEIGHTS: "aff_base_22kto1k_384.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 250
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MAX_ITER: 90000
TEST:
  DETECTIONS_PER_IMAGE: 250
